version: "3"

tasks:
  codegen:
    cmds:
      - npx tsp compile .
      - mkdir -p generated
      - go run github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.0.0 --config oaiconfig.yml tsp-output/@typespec/openapi3/openapi.yaml > generated/server.gen.go
      - go run github.com/sqlc-dev/sqlc/cmd/sqlc@v1.25.0 generate
  format:
    cmds:
      - go fmt ./...
      - npx prettier --write ./db/**/*.sql
