services:
  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  mysql:
    image: mysql:9.2
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - 3306:3306
  sqldef:
    build:
      context: ./docker
      dockerfile: Dockerfile.sqldef
    volumes:
      - ./ddl:/ddl
      - ./scripts:/scripts

volumes:
  db_data: