openapi: 3.0.3
info:
    title: The virtual wine cellar
    description: A simple goa service
    version: "1.0"
servers:
    - url: http://localhost:8080
paths:
    /timeline/public:
        get:
            tags:
                - twitter-clone
            summary: publicTimeline twitter-clone
            operationId: twitter-clone#publicTimeline
            responses:
                "200":
                    description: OK response.
components: {}
tags:
    - name: twitter-clone
      description: Twitter clone
