linters:
    enable-all: true
    disable:
      - depguard # too match for simple structure like this project.
      - goimports # conflict with gofumpt
      - gci # conflict with gofumpt
      - mnd # I think not all magic number is bad. For example, magic number with comment is ok.
linters-settings:
  godot:
    period: false
    capital: false
    check-all: false
  exhaustruct:
    exclude:
      - '.+/huma/v2\.Operation'
  tagalign:
    order: [json, query, header, cookie]
  revive:
    enable-all-rules: true
    ignore-generated-header: true
    rules:
      - name: add-constant # same as mnd
        disabled: true
      - name: unexported-return # I think unexported return is ok.
        disabled: true
      - name: line-length-limit
        arguments: [120]
      - name: nested-structs # I think nested struct is ok.
        disabled: true

