services:
  rdb:
    image: postgres:17
    volumes:
      - rdb-data:/var/lib/postgresql/data
    environment:
      # POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  rdb-data:
