version: '3'

tasks:
  default: task --list-all

  install-deps:
    cmd: go mod tidy
    aliases: [i]
  
  dev:
    cmds:
      - docker compose up -d
      - go run github.com/air-verse/air --build.cmd "go build -o bin/api cmd/main.go" --build.bin "./bin/api"
    aliases: [d]

  fmt:
    cmd: go run mvdan.cc/gofumpt -l -w .
    aliases: [f]

  lint:
    cmd: go run github.com/golangci/golangci-lint/cmd/golangci-lint run ./... {{.CLI_ARGS}}
    aliases: [l]
  lint-fix:
    cmd: task lint -- --fix
    aliases: [lf]

  fmt-schema:
    cmd: task _atlas -- schema fmt schema.hcl
    aliases: [fs]

  migrate-generate:
    cmd: task _atlas -- migrate diff --dir "file://migrations" --to "file://schema.hcl" --dev-url "docker://postgres/15/dev"
    aliases: [mg]

  migrate-apply:
    cmd: task _atlas -- migrate apply --url {{.DATABASE_URL}} --dir "file://migrations"
    vars:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    aliases: [ma]
  
  codegen:
    cmd: go run github.com/go-jet/jet/v2/cmd/jet -dsn=postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable -schema=public -path=./.gen
    aliases: [cg]

  _atlas:
    # cmd: atlas {{.CLI_ARGS}}
    cmd: go run ariga.io/atlas/cmd/atlas {{.CLI_ARGS}}
