services:
  postgres:
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    restart: always