services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.dev
  #   environment:
  #     DB_URL: host=postgres port=5432 user=postgres dbname=postgres password=postgres sslmode=disable
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #   restart: always
  postgres:
    image: postgres:14.6-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    restart: always