// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"bulletproof-go/gen/queries"
	"bulletproof-go/infra/db"
	"bulletproof-go/resolver"
	"bulletproof-go/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializeResolver(_db *sql.DB) *resolver.Resolver {
	queriesQueries := queries.New(_db)
	transactionManager := db.NewTransactionManager(queriesQueries)
	userUseCase := usecase.NewUserUseCase(queriesQueries, transactionManager)
	resolverResolver := resolver.NewResolver(userUseCase)
	return resolverResolver
}
