// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"bulletproof-go/infra/dao"
	"bulletproof-go/infra/db"
	"bulletproof-go/resolver"
	"bulletproof-go/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializeResolver(_db *sql.DB) *resolver.Resolver {
	dbManager := db.NewDbManager(_db)
	userRepository := dao.NewUserDAO(dbManager)
	transactionManager := db.NewTransactionManager(_db)
	userUseCase := usecase.NewUserUseCase(userRepository, transactionManager)
	resolverResolver := resolver.NewResolver(userUseCase)
	return resolverResolver
}
