name: fx-di-gql-ent
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fx-di-gql-ent.yml
      - fx-di-gql-ent/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/fx-di-gql-ent.yml
      - fx-di-gql-ent/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fx-di-gql-ent
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: make lint
      - run: |
          docker compose up -d
          sleep 5
          make test
